homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('profile/', views.index2, name='index2'),
    path('skills/', views.index3, name='index3'),
    path('', views.index, name='index')   
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def index2(request):
    return render(request, 'index2.html')

def index3(request):
    return render(request, 'index3.html')

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Story</title>
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/Story-Style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    <div id="1" class='bg'></div>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #001c62">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'homepage:index' %}">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'homepage:index2' %}">About</a>
                <a class="nav-item nav-link active" href="{% url 'homepage:index3' %}">Skills</a>
              </div>
            </div>
          </nav>
          {% block content %}
          {% endblock %}
</body>
</html>

homepage/templates/index.html
{% extends "base.html" %}



    {% block content %}
    {% load static %}
    
    <div class="container-fluid">
    <div class="row header">
        <div class="col-md my-auto text-center">
            <p class="align-self-end" style="height: 250px">Hi!</p>
            <p style="font-size: 100px">I'm Egi</p>
        </div>
    </div>
    </div>
    {% endblock %}

homepage/templates/index2.html
{% extends "base.html" %}

    {% block content %}
    {% load static %}
    <div class="container-fluid">
    <div class="row profile">
            <div class="col-md-3 my-auto offset-md-1">
                <img src="{% static 'images/319.png' %}">
            </div>
            <div class="col-md offset-md-1">
                <p Style="font-size: 50px; font-weight: bold; padding-top: 5%;">About Me <br></p>
                <p Style="font-size: 12.5%; max-width: 60% ">Hi! I’m Giffari Faqih Phrasya Hardani. 
                        i am a computer science major student at the 
                        University of Indonesia. i love learning 
                        new things and am capable of tackling the 
                        problems that comes with it 
                        in a calm and swift manner</p>
            </div> 
            
        </div>
        <div class="row line">
                <div class="col-md-1">
                    <img src="{% static 'images/line blue.png' %}">
                </div>
                <div class="col-md-2">
                    <p>egiffari</p>
                </div>
        
            </div>
            <div class="row email">
                    <div class="col-md-1">
                        <img src="{% static 'images/gmail.png' %}">
                    </div>
                    <div class="col-md-2">
                        <p>egiffari@gmail.com</p>
                    </div>
            
                </div>
            </div>
    {% endblock %}

homepage/templates/index3.html
{% extends "base.html" %}

    {% block content %}
    {% load static %}
    <div class="container-fluid">
            <div class="row madskillz">
                    <div class="col-sm-2 offset-md-2 text-center">
                        <div class="row skillimage">
                            <img src="{% static 'images/Java_logo.jpg' %}">
                        </div>
                        <div class="row skilldesc">
                             <P>Basic training in Java</P>
                        </div>
                    </div>  
                    <div class="col-sm-2 offset-md-1 text-center">
                        <div class="row skillimage">
                            <img src="{% static 'images/python.png' %}">
                        </div>
                        <div class="row skilldesc">
                            <P>Basic training in Python</P>
                        </div>
                    </div>
                    <div class="col-sm-2 offset-md-1 text-center">
                        <div class="row skillimage">
                            <img src="{% static 'images/C.png' %}">
                        </div>
                        <div class="row skilldesc">
                            <P>Basic training in C</P>
                        </div>
                    </div>
                </div>
    </div>
    {% endblock %}